// =========================
// CATÁLOGO LEGACY DE TOURS RD
// =========================

export const TOUR_CATEGORIES = [
  { key: "tours_diarios", id: "cat_tours_diarios", title: "Tours diarios" },
  { key: "playas", id: "cat_playas", title: "Playas" },
  { key: "montanas", id: "cat_montanas", title: "Montañas" },
  { key: "excursiones_especiales", id: "cat_excursiones_especiales", title: "Excursiones especiales" },
  { key: "paquetes_temporada", id: "cat_paquetes_temporada", title: "Paquetes de temporada" },
];

export const CATEGORY_ID_TO_KEY = Object.fromEntries(TOUR_CATEGORIES.map((c) => [c.id, c.key]));

export function defaultTourCatalog() {
  return [
    {
      key: "city_tour_santo_domingo",
      id: "tour_city_tour_santo_domingo",
      title: "City Tour Santo Domingo",
      category: "tours_diarios",
      origins: ["santo_domingo"],
      description: "Recorrido guiado por la Zona Colonial y puntos icónicos de Santo Domingo.",
      durationMin: 240,
      durationLabel: "4 horas",
      basePriceAdult: 35,
      basePriceChild: 25,
      capacity: 18,
      meetingPoint: "Parque Colón / punto coordinado",
      pickupOptions: "Santo Domingo Centro, Zona Colonial y Gazcue",
      paymentMethods: "Transferencia, efectivo y pago por link",
      reservationPolicy: "Reserva con al menos 24 horas de anticipación.",
      paymentPolicy: "Separa con avance para confirmar tu cupo.",
      includes: ["Transporte interno", "Guía", "Paradas fotográficas"],
      schedule: {
        mon: ["09:00", "15:00"],
        tue: ["09:00", "15:00"],
        wed: ["09:00", "15:00"],
        thu: ["09:00", "15:00"],
        fri: ["09:00", "15:00"],
        sat: ["09:00", "15:00"],
        sun: ["09:00"],
      },
    },
    {
      key: "isla_saona",
      id: "tour_isla_saona",
      title: "Isla Saona",
      category: "playas",
      origins: ["santo_domingo", "punta_cana"],
      description: "Excursión de día completo con playa, lancha/catamarán y ambiente caribeño.",
      durationMin: 720,
      durationLabel: "Día completo",
      basePriceAdult: 95,
      basePriceChild: 75,
      capacity: 24,
      meetingPoint: "Punto de salida coordinado según zona",
      pickupOptions: "Santo Domingo, Boca Chica, La Romana, Punta Cana",
      paymentMethods: "Transferencia, efectivo y pago por link",
      reservationPolicy: "Reserva con 48 horas de anticipación.",
      paymentPolicy: "Requiere avance para bloquear espacios.",
      includes: ["Transporte", "Guía", "Almuerzo", "Bebidas"],
      schedule: {
        mon: ["06:00"],
        tue: ["06:00"],
        wed: ["06:00"],
        thu: ["06:00"],
        fri: ["06:00"],
        sat: ["06:00"],
        sun: ["06:00"],
      },
    },
    {
      key: "isla_catalina",
      id: "tour_isla_catalina",
      title: "Isla Catalina",
      category: "playas",
      origins: ["santo_domingo", "punta_cana"],
      description: "Tour ideal para disfrutar de playa, snorkeling y día relajado.",
      durationMin: 660,
      durationLabel: "Día completo",
      basePriceAdult: 89,
      basePriceChild: 69,
      capacity: 20,
      meetingPoint: "Punto de salida coordinado según zona",
      pickupOptions: "Santo Domingo, La Romana y Punta Cana",
      paymentMethods: "Transferencia, efectivo y pago por link",
      reservationPolicy: "Reserva con 48 horas de anticipación.",
      paymentPolicy: "Avance obligatorio para confirmar.",
      includes: ["Transporte", "Guía", "Snorkeling", "Almuerzo"],
      schedule: {
        mon: ["06:30"],
        wed: ["06:30"],
        fri: ["06:30"],
        sat: ["06:30"],
      },
    },
    {
      key: "jarabacoa_aventura",
      id: "tour_jarabacoa_aventura",
      title: "Jarabacoa Aventura",
      category: "montanas",
      origins: ["santo_domingo"],
      description: "Ruta de montaña con paisajes, río y paradas fotográficas.",
      durationMin: 720,
      durationLabel: "Día completo",
      basePriceAdult: 70,
      basePriceChild: 55,
      capacity: 16,
      meetingPoint: "Santo Domingo / Santiago según grupo",
      pickupOptions: "Santo Domingo, Santiago",
      paymentMethods: "Transferencia y efectivo",
      reservationPolicy: "Reserva con 48 horas de anticipación.",
      paymentPolicy: "Separa con avance.",
      includes: ["Transporte", "Guía", "Paradas", "Hidratación"],
      schedule: {
        sat: ["06:00"],
        sun: ["06:00"],
      },
    },
    {
      key: "buggies_macao",
      id: "tour_buggies_macao",
      title: "Buggies Macao",
      category: "excursiones_especiales",
      origins: ["punta_cana"],
      description: "Aventura en buggies con playa y recorrido guiado.",
      durationMin: 300,
      durationLabel: "5 horas",
      basePriceAdult: 65,
      basePriceChild: 50,
      capacity: 12,
      meetingPoint: "Punta Cana / punto coordinado",
      pickupOptions: "Punta Cana, Bávaro, Uvero Alto",
      paymentMethods: "Transferencia, efectivo y link de pago",
      reservationPolicy: "Reserva con 24 horas de anticipación.",
      paymentPolicy: "Avance para confirmar.",
      includes: ["Transporte", "Guía", "Equipo básico"],
      schedule: {
        mon: ["08:00", "13:00"],
        tue: ["08:00", "13:00"],
        wed: ["08:00", "13:00"],
        thu: ["08:00", "13:00"],
        fri: ["08:00", "13:00"],
        sat: ["08:00", "13:00"],
      },
    },
    {
      key: "samana_temporada",
      id: "tour_samana_temporada",
      title: "Samaná Temporada",
      category: "paquetes_temporada",
      origins: ["santo_domingo", "las_terrenas"],
      description: "Paquete especial de temporada con transporte y experiencia guiada.",
      durationMin: 900,
      durationLabel: "Día completo",
      basePriceAdult: 120,
      basePriceChild: 95,
      capacity: 22,
      meetingPoint: "Punto coordinado según ciudad",
      pickupOptions: "Santo Domingo, San Pedro, La Romana y Las Terrenas",
      paymentMethods: "Transferencia, efectivo y pago por link",
      reservationPolicy: "Sujeto a temporada y cupos disponibles.",
      paymentPolicy: "Avance obligatorio para confirmar cupo.",
      includes: ["Transporte", "Guía", "Almuerzo", "Actividad principal"],
      activeMonths: [1, 2, 3],
      schedule: {
        fri: ["05:30"],
        sat: ["05:30"],
        sun: ["05:30"],
      },
    },
  ];
}

const TOURS = defaultTourCatalog();
const TOUR_ID_TO_KEY = Object.fromEntries(TOURS.map((t) => [t.id, t.key]));
