// =========================
// CATÁLOGO REAL DE TOURS - COLOMBIA
// =========================

const COLOMBIA_TOUR_IMAGES = {
  tour_por_antioquia: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984226/WhatsApp_Image_2026-03-19_at_8.49.46_PM_y6lvsf.jpg",
  guatape_piedra_penol: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984226/WhatsApp_Image_2026-03-19_at_8.49.45_PM_3_ufaouv.jpg",
  parque_napoles_santorini: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984225/WhatsApp_Image_2026-03-19_at_8.49.46_PM_1_nynngj.jpg",
  ruta_de_la_leche: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984224/WhatsApp_Image_2026-03-19_at_8.49.45_PM_sszyxq.jpg",
  concepcion_el_canelo: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984224/WhatsApp_Image_2026-03-19_at_8.49.45_PM_2_z3ngj2.jpg",
  jardin_hispania_andes: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984223/WhatsApp_Image_2026-03-19_at_8.49.45_PM_1_vbrbpk.jpg",
  buga_y_los_termales: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984223/WhatsApp_Image_2026-03-19_at_8.49.44_PM_kbnmss.jpg",
  termales_espiritu_santo: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984222/WhatsApp_Image_2026-03-19_at_8.49.44_PM_1_canpzt.jpg",
  pueblos_encanto_suroeste: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984221/WhatsApp_Image_2026-03-19_at_8.49.43_PM_1_owjhqc.jpg",
  santorini_antioqueno: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984220/WhatsApp_Image_2026-03-19_at_8.49.42_PM_j5vkik.jpg",
  cisneros_entre_rieles_montanas: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984220/WhatsApp_Image_2026-03-19_at_8.49.42_PM_4_td5isy.jpg",
  jerico_1_dia: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984220/WhatsApp_Image_2026-03-19_at_8.49.42_PM_2_u3m6k9.jpg",
  santa_fe_kanaloa: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984220/WhatsApp_Image_2026-03-19_at_8.49.42_PM_3_nikmoc.jpg",
  amalfi_1_dia: "https://res.cloudinary.com/daqqrtg0b/image/upload/v1773984219/WhatsApp_Image_2026-03-19_at_8.49.41_PM_tzh5nv.jpg",
  comuna_13_grafitour: "",
};

export const REAL_TOUR_GROUPS = [
  { key: "tours_1_dia", id: "rtg_tours_1_dia", title: "Tours de 1 día" },
  { key: "tours_2_dias", id: "rtg_tours_2_dias", title: "Tours de 2 días o más" },
  { key: "experiencias_city_tours", id: "rtg_experiencias_city_tours", title: "Experiencias y city tours" },
  { key: "salidas_especiales", id: "rtg_salidas_especiales", title: "Salidas especiales" },
];

export const REAL_TOUR_GROUP_ID_TO_KEY = Object.fromEntries(
  REAL_TOUR_GROUPS.map((g) => [g.id, g.key])
);

export function buildRealToursCatalog() {
  return [
    {
      key: "guatape_piedra_penol",
      id: "rt_guatape_piedra_penol",
      title: "Guatapé – Piedra del Peñol",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.guatape_piedra_penol,
      leadOnly: true,
    },
    {
      key: "ruta_de_la_leche",
      id: "rt_ruta_de_la_leche",
      title: "Ruta de la Leche",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.ruta_de_la_leche,
      leadOnly: true,
    },
    {
      key: "concepcion_el_canelo",
      id: "rt_concepcion_el_canelo",
      title: "Concepción – El Canelo",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.concepcion_el_canelo,
      leadOnly: true,
    },
    {
      key: "jardin_hispania_andes",
      id: "rt_jardin_hispania_andes",
      title: "Jardín – Hispania y Andes",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.jardin_hispania_andes,
      leadOnly: true,
    },
    {
      key: "santorini_antioqueno",
      id: "rt_santorini_antioqueno",
      title: "Santorini Antioqueño",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.santorini_antioqueno,
      leadOnly: true,
    },
    {
      key: "cisneros_entre_rieles_montanas",
      id: "rt_cisneros_entre_rieles_montanas",
      title: "Cisneros – Entre Rieles y Montañas",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.cisneros_entre_rieles_montanas,
      leadOnly: true,
    },
    {
      key: "jerico_1_dia",
      id: "rt_jerico_1_dia",
      title: "Jericó – Tour de 1 día",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.jerico_1_dia,
      leadOnly: true,
    },
    {
      key: "santa_fe_kanaloa",
      id: "rt_santa_fe_kanaloa",
      title: "Santa Fe / Kanaloa",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.santa_fe_kanaloa,
      leadOnly: true,
    },
    {
      key: "amalfi_1_dia",
      id: "rt_amalfi_1_dia",
      title: "Amalfi – Tour de 1 día",
      groupKey: "tours_1_dia",
      imageUrl: COLOMBIA_TOUR_IMAGES.amalfi_1_dia,
      leadOnly: true,
    },
    {
      key: "parque_napoles_santorini",
      id: "rt_parque_napoles_santorini",
      title: "Parque Temático Nápoles + Santorini Antioqueño",
      groupKey: "tours_2_dias",
      imageUrl: COLOMBIA_TOUR_IMAGES.parque_napoles_santorini,
      leadOnly: true,
    },
    {
      key: "termales_espiritu_santo",
      id: "rt_termales_espiritu_santo",
      title: "Termales del Espíritu Santo – Nariño Antioquia",
      groupKey: "tours_2_dias",
      imageUrl: COLOMBIA_TOUR_IMAGES.termales_espiritu_santo,
      leadOnly: true,
    },
    {
      key: "buga_y_los_termales",
      id: "rt_buga_y_los_termales",
      title: "Buga y Los Termales",
      groupKey: "tours_2_dias",
      imageUrl: COLOMBIA_TOUR_IMAGES.buga_y_los_termales,
      leadOnly: true,
    },
    {
      key: "pueblos_encanto_suroeste",
      id: "rt_pueblos_encanto_suroeste",
      title: "Pueblos de Encanto del Suroeste Antioqueño",
      groupKey: "tours_2_dias",
      imageUrl: COLOMBIA_TOUR_IMAGES.pueblos_encanto_suroeste,
      leadOnly: true,
    },
    {
      key: "comuna_13_grafitour",
      id: "rt_comuna_13_grafitour",
      title: "Comuna 13 Grafitour",
      groupKey: "experiencias_city_tours",
      imageUrl: COLOMBIA_TOUR_IMAGES.comuna_13_grafitour,
      leadOnly: true,
    },
    {
      key: "tour_por_antioquia",
      id: "rt_tour_por_antioquia",
      title: "Tour por Antioquia",
      groupKey: "salidas_especiales",
      imageUrl: COLOMBIA_TOUR_IMAGES.tour_por_antioquia,
      leadOnly: true,
    },
  ];
}

export const REAL_TOUR_TEXT_OVERRIDES = {
  guatape_piedra_penol: {
    priceText: "Desde COP 129.000 por persona.",
    durationText: "Tour de 1 día.",
    dateText: "Salidas todos los días.",
    pickupText: "Puntos de encuentro: Metro Poblado y Metro Estadio.",
    includesText: "Transporte ida y vuelta, desayuno, almuerzo, tour en barco, asistencia médica, visita a Piedra del Peñol (ascenso no incluido), Guatapé y réplica, Alto del Chocho y guía experto.",
    paymentText: "Tarifa sujeta a disponibilidad y actualización por la agencia.",
    reserveText: "Reserva sujeta a cupos y validación final por parte del asesor.",
    noteText: "La imagen promocional oficial ya está cargada en esta ficha.",
  },
  ruta_de_la_leche: {
    priceText: "COP 178.000 por persona.",
    durationText: "Tour de 1 día.",
    dateText: "Fechas programadas por meses según calendario vigente.",
    pickupText: "Puntos de encuentro: C.C. Mayorca, Estación Poblado, Av. Oriental / Panadería Al Pan Pan y C.C. Mega Norte.",
    includesText: "Transporte ida y vuelta, desayuno, almuerzo, visita a Hoyo Rico, Santa Rosa y San Pedro, Granja de Fe, Plaza del Río, tarjeta de asistencia médica y guía experto.",
    paymentText: "Tarifa sujeta a cupo y salida vigente.",
    reserveText: "Se recomienda reservar según las fechas programadas publicadas por la agencia.",
    noteText: "Confirma con el asesor la salida exacta que deseas tomar.",
  },
  concepcion_el_canelo: {
    priceText: "COP 160.000 por persona.",
    durationText: "Tour de 1 día.",
    dateText: "Fechas programadas por la agencia.",
    pickupText: "Puntos de encuentro: C.C. Mayorca, Estación Poblado, Panadería Al Pan Pan y Terminal del Norte.",
    includesText: "Transporte ida y vuelta, desayuno, almuerzo, Cascada Matasanos, visitas guiadas, asistencia médica y guía experto.",
    paymentText: "Tarifa sujeta a disponibilidad.",
    reserveText: "Solicita tu salida preferida y el asesor valida cupo.",
    noteText: "Ideal para clientes que buscan naturaleza y plan full day.",
  },
  jardin_hispania_andes: {
    priceText: "Plan básico COP 150.000 | Plan full COP 165.000.",
    durationText: "Tour de 1 día.",
    dateText: "Salidas sábados y domingos.",
    pickupText: "Puntos de encuentro: Panadería Al Pan Pan y C.C. Mayorca.",
    includesText: "Transporte ida y vuelta, desayuno, almuerzo en truchera, visitas a Hispania, Andes y Jardín, tarjeta de asistencia médica y guía experto. El plan full añade arroz con leche, walking tour con guía local y recorrido en trencito.",
    paymentText: "La tarifa depende del plan elegido.",
    reserveText: "Indica al asesor si deseas plan básico o plan full.",
    noteText: "El plan full incluye extras experienciales dentro del recorrido.",
  },
  santorini_antioqueno: {
    priceText: "Día de sol COP 180.000 | Rafting COP 230.000.",
    durationText: "Tour de 1 día.",
    dateText: "Salidas programadas por la agencia.",
    pickupText: "Puntos de encuentro sujetos a la salida seleccionada.",
    includesText: "Plan de día con recorrido al Santorini Antioqueño. La modalidad de rafting incluye experiencia de aventura adicional.",
    paymentText: "La tarifa depende de la modalidad seleccionada.",
    reserveText: "Indica al asesor si te interesa día de sol o rafting.",
    noteText: "La modalidad exacta se confirma con la agencia antes del pago.",
  },
  cisneros_entre_rieles_montanas: {
    priceText: "COP 180.000 por persona.",
    durationText: "Tour de 1 día.",
    dateText: "Fechas programadas por la agencia.",
    pickupText: "Puntos de encuentro sujetos a la salida vigente.",
    includesText: "Transporte, recorrido guiado y experiencia turística en Cisneros y sus paisajes.",
    paymentText: "Tarifa referencial sujeta a validación.",
    reserveText: "Consulta las salidas vigentes para tu fecha de interés.",
    noteText: "La logística final se confirma antes de reservar.",
  },
  jerico_1_dia: {
    priceText: "Desde COP 160.000 por persona.",
    durationText: "Tour de 1 día.",
    dateText: "Fechas programadas por la agencia.",
    pickupText: "Puntos de encuentro sujetos a la salida seleccionada.",
    includesText: "Transporte y recorrido guiado por Jericó con agenda según la salida publicada.",
    paymentText: "Tarifa sujeta a disponibilidad.",
    reserveText: "Solicita tu fecha y el asesor confirma cupo.",
    noteText: "Perfecto para clientes interesados en pueblo patrimonial y plan de día.",
  },
  santa_fe_kanaloa: {
    priceText: "Desde COP 175.000 por persona.",
    durationText: "Tour de 1 día.",
    dateText: "Fechas programadas por la agencia.",
    pickupText: "Puntos de encuentro sujetos a la salida vigente.",
    includesText: "Plan de día a Santa Fe / Kanaloa con transporte y actividades según programación.",
    paymentText: "Tarifa sujeta a cupo y salida seleccionada.",
    reserveText: "Consulta con el asesor la fecha disponible más conveniente.",
    noteText: "El detalle final de actividades se confirma al reservar.",
  },
  amalfi_1_dia: {
    priceText: "Desde COP 210.000 por persona.",
    durationText: "Tour de 1 día.",
    dateText: "Fechas programadas por la agencia.",
    pickupText: "Puntos de encuentro sujetos a la salida vigente.",
    includesText: "Recorrido full day a Amalfi con transporte y acompañamiento según la salida publicada.",
    paymentText: "Tarifa sujeta a actualización.",
    reserveText: "Solicita tu fecha ideal y te validamos la próxima salida.",
    noteText: "Se confirma logística final al momento de reservar.",
  },
  parque_napoles_santorini: {
    priceText: "Pasaporte Safari desde COP 599.000 | Pasaporte Premium desde COP 660.000.",
    durationText: "Tour de 2 días.",
    dateText: "Salidas programadas por calendario.",
    pickupText: "Puntos de encuentro: Estación Estadio, Av. Oriental y Parque del Poblado.",
    includesText: "Transporte ida y vuelta, 2 desayunos, 1 almuerzo, 1 cena, 1 noche de hotel con piscina, ingreso a Hacienda Nápoles según pasaporte, visita al Santorini Antioqueño, guía y tarjeta médica.",
    paymentText: "Para acomodación doble incrementa 10%. La tarifa depende del pasaporte seleccionado.",
    reserveText: "Indica si deseas Pasaporte Safari o Premium.",
    noteText: "La agencia confirma cupo, fecha y tipo de acomodación antes del pago.",
  },
  termales_espiritu_santo: {
    priceText: "Desde COP 470.000 por persona en múltiple.",
    durationText: "Plan con 1 noche.",
    dateText: "Salidas programadas por la agencia.",
    pickupText: "Puntos de encuentro sujetos a la salida vigente.",
    includesText: "Plan con transporte, alojamiento, alimentación e ingreso a termales según la salida publicada.",
    paymentText: "Tarifa referencial sujeta a acomodación y fecha.",
    reserveText: "Confirma tu fecha para validar tarifa final y cupo.",
    noteText: "El asesor valida la acomodación disponible según la salida.",
  },
  buga_y_los_termales: {
    priceText: "Múltiple COP 560.000 | Doble COP 610.000 por persona.",
    durationText: "Plan con 1 noche.",
    dateText: "Fechas de salida 2026 publicadas por la agencia.",
    pickupText: "Punto de encuentro: Metro Suramericana.",
    includesText: "Transporte, 1 noche de alojamiento en finca hotel, 1 cena, 2 desayunos, 2 almuerzos, ingreso a termales, Milagroso de Buga, Santa Rosa de Cabal, guía profesional y tarjeta médica.",
    paymentText: "La tarifa depende del tipo de acomodación.",
    reserveText: "Indica si viajas en acomodación múltiple o doble.",
    noteText: "La salida exacta y condiciones finales se confirman al reservar.",
  },
  pueblos_encanto_suroeste: {
    priceText: "Desde COP 630.000 por persona.",
    durationText: "Plan con 2 noches en Jardín.",
    dateText: "Salidas 2026 programadas por la agencia.",
    pickupText: "Puntos de encuentro sujetos a la salida publicada.",
    includesText: "Circuito turístico por pueblos del suroeste antioqueño con transporte, alojamiento, recorridos y servicios según la promoción vigente.",
    paymentText: "Tarifa sujeta a acomodación, fecha y cupo disponible.",
    reserveText: "Solicita la fecha que te interesa y el asesor valida la próxima salida.",
    noteText: "Ideal para clientes que desean un plan de varios días con pueblos y paisajes.",
  },
  comuna_13_grafitour: {
    priceText: "Desde COP 110.000 por persona.",
    durationText: "Experiencia urbana / city tour.",
    dateText: "Salidas según programación de la agencia.",
    pickupText: "Punto de encuentro sujeto a la experiencia seleccionada.",
    includesText: "Recorrido guiado por Comuna 13 con enfoque cultural, artístico y urbano.",
    paymentText: "Tarifa sujeta a modalidad y disponibilidad.",
    reserveText: "Solicita la experiencia y horario que deseas reservar.",
    noteText: "La imagen de esta experiencia puede cargarse más adelante si deseas una pieza específica.",
  },
  tour_por_antioquia: {
    priceText: "Tarifa según salida vigente publicada por la agencia.",
    durationText: "Fin de semana / 2 días según salida.",
    dateText: "Salidas programadas por la agencia.",
    pickupText: "Salida publicada desde Éxito Robledo en la pieza compartida.",
    includesText: "Hotel, piscina, comidas y bebidas, staff profesional, transporte y recorrido por San Jerónimo, Santa Fe y Sopetrán según la promoción compartida.",
    paymentText: "Tarifa sujeta a fecha, cupo y condiciones de la salida vigente.",
    reserveText: "Solicita la salida que te interesa y el asesor confirma disponibilidad.",
    noteText: "La logística exacta depende de la programación activa de la agencia.",
  },
};
